<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Jobs\ProcessDemoJob;
use App\Models\UploadedDemo;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;

/**
 * Endpoints consumed by the desktop launcher (tauri app). All routes are
 * authenticated via a personal access token with ability "launcher:upload".
 * Token is generated by the user at /user/launcher-tokens and pasted into
 * the launcher once. Every request carries `Authorization: Bearer <token>`.
 */
class LauncherController extends Controller
{
    /**
     * Given an MD5 hash of a demo file, tell the launcher whether it already
     * exists on the server. Prevents re-uploading demos that were previously
     * backed up (e.g. after a reinstall) or were uploaded through the web.
     *
     * Expected body:   { "hash": "<32-char md5>" }
     * Response 200:    { "exists": bool, "demo_id": int|null }
     */
    public function lookupByHash(Request $request)
    {
        $data = $request->validate([
            'hash' => 'required|string|size:32',
        ]);

        $demo = UploadedDemo::where('file_hash', strtolower($data['hash']))
            ->first(['id']);

        return response()->json([
            'exists' => $demo !== null,
            'demo_id' => $demo?->id,
        ]);
    }

    /**
     * Single-file demo upload. The launcher calls /lookup-by-hash first, so
     * duplicates are the exception, not the rule — we still defend against
     * them because two launchers on different PCs could race on the same
     * demo.
     *
     * Expected multipart body:
     *   demo     (file, .dm_68/.dm_69 etc.)
     *   hash     (optional md5; if omitted we compute it server-side)
     *
     * Response 200: { "demo_id": int, "status": "uploaded" }
     * Response 409: { "error": "duplicate", "demo_id": int }
     */
    public function uploadDemo(Request $request)
    {
        $user = $request->user();

        if (! $user->canUploadDemos()) {
            return response()->json([
                'error' => 'Your account has been restricted from uploading demos.',
            ], 403);
        }

        $request->validate([
            'demo' => 'required|file|max:512000', // 512 MB, same cap as the web form
            'hash' => 'nullable|string|size:32',
        ]);

        $file = $request->file('demo');
        $originalName = $file->getClientOriginalName();
        $extension = strtolower($file->getClientOriginalExtension());

        if (! preg_match('/^dm_\d+$/', $extension)) {
            return response()->json([
                'error' => 'Invalid demo file extension (expected dm_68/dm_69/...).',
            ], 422);
        }

        $hash = strtolower($request->input('hash') ?: md5_file($file->getPathname()));

        // Short-circuit: if the hash is already in the DB, treat as duplicate.
        // Returning 409 so the launcher can skip + mark local demo as "already backed up".
        $existing = UploadedDemo::where('file_hash', $hash)->first(['id', 'status']);
        if ($existing) {
            return response()->json([
                'error' => 'duplicate',
                'demo_id' => $existing->id,
                'status' => $existing->status,
            ], 409);
        }

        $demo = UploadedDemo::create([
            'original_filename' => $originalName,
            'file_path' => '',
            'file_size' => $file->getSize(),
            'file_hash' => $hash,
            'user_id' => $user->id,
            'status' => 'uploaded',
        ]);

        $directory = storage_path("app/demos/temp/{$demo->id}");
        if (! is_dir($directory)) {
            mkdir($directory, 0755, true);
        }
        $file->move($directory, $originalName);
        $demo->update(['file_path' => "demos/temp/{$demo->id}/{$originalName}"]);

        ProcessDemoJob::dispatch($demo);

        Log::info('Launcher demo upload', [
            'user_id' => $user->id,
            'demo_id' => $demo->id,
            'hash' => $hash,
            'size' => $demo->file_size,
        ]);

        return response()->json([
            'demo_id' => $demo->id,
            'status' => 'uploaded',
        ]);
    }
}
