[package]
name = "defrag_rating"
version = "0.1.0"
edition = "2021"

[dependencies]
mysql = "25.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rayon = "1.10"
chrono = { version = "0.4", features = ["serde"] }
